### ISSUE TITLE
Create installer

### ISSUE THREAD

**Issue by forman** [CCI-Tools/ect-core#10]
So far, ECT has no installer which would include a deeply freezed Conda Python environment and provides Desktop/Startmenu shortcuts for the CLI (and later include the frontend binaries and shortcuts).

See also wiki page [Software Installation Approach](https://github.com/CCI-Tools/ect-core/wiki/Software-Installation-Approach).

**Comment by JanisGailis** [comment]
I have used Bitrock Installbuilder for bundling everything together and creating an installer. The downside is that the resulting installer is an *.exe for windows and a graphical installer for Linux and Max, that seems a bit out of place for those systems. It is free to use for Open Sourced projects:
https://installbuilder.bitrock.com/

Before using the installer I had to freeze the environment. Mine was a Conda environment as well. I used PyInstaller for Windows and Linux (if I recall correctly), I had some issues with getting PyQt and Qt being frozen properly on Linux, mainly because I would get some system libraries (Gtk and stuff) frozen into the package that had to be removed by hand so that the resulting application would use system Gtk. But this only applies to a GUI that uses the underlying desktop environment from Python.

I also had a problem on Windows that it wouldn't gather all the required *.dll files. But again this was because of the Qt GUI, I think!

We can talk about this during the next devmeeting.

**Comment by lkeupp** [comment]
In my opinion an installer that brings everything needed for ECT to be properly installed is really important for the user. 
Even the higher-level users are not neccessarily competent regarding using python and installing dependencies manually.

**Comment by forman** [comment]
My suggestion is to exploit the capabilities of the Anaconda installer by creating a customized version of it. This is what we already (successfully) did in the DeDop project: https://github.com/DeDop/dedop-conda

The Anaconda installer installs a complete, isolated Python and can be configured to include any extra packages, such as `ect`. It can also create Startmenu entries (Windows only).

However, once we have the ECT GUI, this option may no longer be applicable as we might need much better Desktop integration features for all the OS platforms.

**Comment by JanisGailis** [comment]
This sounds good, at least for v1.0.

Later we can see if we can script what we need for Desktop integration and add it to the Anaconda installation routine, or, we can try to use, say, InstallBuilder together with Anaconda installer to get fancier desktop integration.

**Comment by forman** [comment]
Scripts to create the ECT Conda package and a Conda Installer are now in [ect-conda](https://github.com/CCI-Tools/ect-conda) repo. Follow its [README](https://github.com/CCI-Tools/ect-conda/blob/master/README.md) to create a Conda package and installer for individual OS platforms.
